[Unit]
Requires=telegram-proxy-tunnel.service
After=telegram-proxy-tunnel.service

[Service]
Environment="HTTPS_PROXY=http://127.0.0.1:8888"
Environment="HTTP_PROXY=http://127.0.0.1:8888"
Environment="NO_PROXY=127.0.0.1,localhost,api.cloudflare.com,ru.goida.fun,web.goida.fun"
