server {
    listen 80;
    listen [::]:80;
    server_name vpndeployer.ru www.vpndeployer.ru;

    root /var/www/vpndeployer;
    index index.html;

    location / {
        try_files $uri $uri/ =404;
    }
}
